version: "3.9"

services:
  influxdb:
    container_name: "influxdb"
    image: "influxdb:2.1-alpine"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influx.${HOST}`)"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=myresolver"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
      - "traefik.http.middlewares.influxdbsts.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.influxdbsts.headers.stspreload=true"
      - "traefik.http.middlewares.influxdbsts.headers.stsseconds=31536000"
      - "traefik.http.middlewares.influxdbsts.headers.isdevelopment=false"
      - "traefik.http.routers.influxdb.middlewares=influxdbsts"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_conf:/etc/influxdb2
    networks:
      net:
    ports:
      - "8086:8086"
    environment:
      - TZ=Europe/Berlin
      
volumes:
  influxdb_data:
  influxdb_conf:
  
networks:
  net:
    external:
      name: traefik_net
